### ISSUE TITLE
Issue InteractionGymEquipment.onWalkOff - 3.5.0

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#1014]
In GitLab by @ColicDusti on Apr 21, 2022, 15:49

 

## Build Information

Emulator Version:  
Emulator Build (hash):

## Current Behavior

Bug on Emulator regarding InteractionGymEquipment
## Possible Solution

I don't know how to fix it
## Steps to Reproduce

1. I don't know have tested a lot of thing afk and leave / enter gym equipment and leave.
1.
1.
1.

ONE LINE ISSUE - 
15:30:28.704 [GameWorker-4-3] ERROR com.eu.habbo.habbohotel.rooms.Room - Caught exception
java.lang.NullPointerException: null
	at com.eu.habbo.habbohotel.rooms.Room.giveEffect(Room.java:4129)
	at com.eu.habbo.habbohotel.items.interactions.InteractionGymEquipment.onWalkOff(InteractionGymEquipment.java:58)
	at com.eu.habbo.habbohotel.rooms.Room.removeHabbo(Room.java:2689)
	at com.eu.habbo.habbohotel.rooms.RoomManager.leaveRoom(RoomManager.java:947)
	at com.eu.habbo.habbohotel.rooms.RoomManager.leaveRoom(RoomManager.java:939)
	at com.eu.habbo.habbohotel.users.Habbo.disconnect(Habbo.java:169)
	at com.eu.habbo.habbohotel.gameclients.GameClient.dispose(GameClient.java:116)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager.disposeClient(GameClientManager.java:52)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager.access$000(GameClientManager.java:14)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager$1.operationComplete(GameClientManager.java:33)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager$1.operationComplete(GameClientManager.java:30)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

SECOND ISSUE BUT SAME BUT IT ADD'S WEBSOCKETS LINES - 

18:44:48.330 [GameWorker-4-3] ERROR com.eu.habbo.habbohotel.rooms.Room - Caught exception
java.lang.NullPointerException: null
	at com.eu.habbo.habbohotel.rooms.Room.giveEffect(Room.java:4129)
	at com.eu.habbo.habbohotel.items.interactions.InteractionGymEquipment.onWalkOff(InteractionGymEquipment.java:58)
	at com.eu.habbo.habbohotel.rooms.Room.removeHabbo(Room.java:2689)
	at com.eu.habbo.habbohotel.rooms.RoomManager.leaveRoom(RoomManager.java:947)
	at com.eu.habbo.habbohotel.rooms.RoomManager.leaveRoom(RoomManager.java:939)
	at com.eu.habbo.habbohotel.users.Habbo.disconnect(Habbo.java:169)
	at com.eu.habbo.habbohotel.gameclients.GameClient.dispose(GameClient.java:116)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager.disposeClient(GameClientManager.java:52)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager.access$000(GameClientManager.java:14)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager$1.operationComplete(GameClientManager.java:33)
	at com.eu.habbo.habbohotel.gameclients.GameClientManager$1.operationComplete(GameClientManager.java:30)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.handler.logging.LoggingHandler.close(LoggingHandler.java:247)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$1.operationComplete(WebSocketProtocolHandler.java:102)
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$1.operationComplete(WebSocketProtocolHandler.java:99)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.close(WebSocketServerHandshaker.java:356)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.close(WebSocketServerHandshaker.java:341)
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler.decode(WebSocketServerProtocolHandler.java:240)
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler.decode(WebSocketServerProtocolHandler.java:53)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

HOPE I HELP MY BEST :disappointed:

**Comment by brenoepics** [comment]
In GitLab by @ghost on Apr 21, 2022, 20:17

that's a long ass error ngl

**Comment by brenoepics** [comment]
In GitLab by @ColicDusti on Apr 21, 2022, 20:50

I know Oliver if i know how to reproduce it i'll let it here. :smile:

**Comment by brenoepics** [comment]
In GitLab by @Pepsiman on Jul 20, 2022, 19:29

mentioned in commit Pepsiman/Arcturus-Community@2522e1ce4af215d1a5d2dfc4580eab1d60dab5e5
