### ISSUE TITLE
Issue on ubuntu 18.04

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#439]
In GitLab by @Brianelvio on Feb 12, 2020, 18:29

 

## Build Information

Emulator Version: 2-3-0-rc2
Emulator Build (hash): 20cdf371c20be6e5d92fe6d08fd6317e

## What is the error?
```
[LOADING] Hotelview Manager -> Loaded! (3 MS)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.eu.habbo.habbohotel.items.ItemManager.<init>(ItemManager.java:85)
	at com.eu.habbo.habbohotel.GameEnvironment.load(GameEnvironment.java:57)
	at com.eu.habbo.Emulator.main(Emulator.java:123)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Locale.<init>(Locale.java:713)
	at java.base/java.util.Locale.<init>(Locale.java:742)
	at com.eu.habbo.habbohotel.wired.highscores.WiredHighscoreManager.<clinit>(WiredHighscoreManager.java:22)
	... 3 more
```

## When does this error occur?

This issue occurs when starting the server on Ubuntu 18.04
The same jar runs fine on OSX at the moment.

I've tried every version of JDK & JRE available.
Currently using the same Java version as I use on my OSX box where it works just fine.

java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

## What is the outcome of this error?

The emulator can't initialize / start.

## Steps to Reproduce

1. Ubuntu 18.04 VM
2. java -jar Habbo-2.3.0-jar-with-dependencies.jar
3. See the error as above.

**Comment by brenoepics** [comment]
In GitLab by @Robb on Apr 19, 2022, 18:10

Hi guys, I got this problem even with 3.0.0 Morningstar and newer Java version (OpenJDK 11), and after a while I figure it out. It's the server locale the problem. I had LC_ALL set to "C.UTF_8" but the emulator requires "en_US.UTF_8". To set the locale of your server to en_US.UTF_8 do this commands on terminal (that's on Ubuntu, may differ by OS):

Generate the locale
`sudo locale-gen en_US.UTF-8`

Update your locale settings
`sudo update-locale LC_ALL=en_US.UTF-8`

and apply with this command 
`. /etc/default/locale`

After that you shouldn't see this error and the emulator should start.
