### ISSUE TITLE
Gift-system improvements & NPE

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#602]
In GitLab by @ghost on May 5, 2020, 08:44

Some random bugs I found scattered around the gift system in my Hotel.

## NPE for opening gifts
Has something to do with `i.setUserId(this.habbo.getHabboInfo().getId());`.

* [ ] NPE
```
java.lang.NullPointerException
	at com.eu.habbo.threading.runnables.OpenGift.run(OpenGift.java:41)
	at com.eu.habbo.threading.ThreadPooling.lambda$run$0(ThreadPooling.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

## Sending a badge as an gift
* [ ] Badge gift
This appears to work, then doesn't. That's it. Nothing extra to it.

```                     
case BADGE:
                        if (!unseenItems.containsKey(AddHabboItemComposer.AddHabboItemCategory.BADGE))
                            unseenItems.put(AddHabboItemComposer.AddHabboItemCategory.BADGE, new ArrayList<>());

                        unseenItems.get(AddHabboItemComposer.AddHabboItemCategory.BADGE).add(item.getId()); // badges cannot be placed so no need for gift adjusted ID
                        break;
```

## Sending a pet as an gift
* [ ] Pet gift
This purely results as an error, nothing bad. Can't get the packets for this one. Sorry 'bout that. This one results as just a basic "Error happened"-alert.

```                    
case PET:
                        if (!unseenItems.containsKey(AddHabboItemComposer.AddHabboItemCategory.PET))
                            unseenItems.put(AddHabboItemComposer.AddHabboItemCategory.PET, new ArrayList<>());

                        unseenItems.get(AddHabboItemComposer.AddHabboItemCategory.PET).add(item.getGiftAdjustedId());
                        break;
```

## Sending a bot as an gift
* [ ] Bot gift

```                    
case ROBOT:
                        if (!unseenItems.containsKey(AddHabboItemComposer.AddHabboItemCategory.BOT))
                            unseenItems.put(AddHabboItemComposer.AddHabboItemCategory.BOT, new ArrayList<>());

                        unseenItems.get(AddHabboItemComposer.AddHabboItemCategory.BOT).add(item.getGiftAdjustedId());
                        break;
```

Can't get the packets for this one. Sorry 'bout that. This bug results in an black box in your inventory, as Arc tries to send it as an normal item, where as it should be an actual bot. Upon placing the "black box", you disconnect. It becomes invisible until you :pickall.

# No errors to provide, I do have an .GIF though.
https://gyazo.com/e161d95a44f68f7b13b0476683667230

**Comment by brenoepics** [comment]
In GitLab by @Remco on Mar 3, 2022, 11:38

marked the checklist item **NPE** as completed

**Comment by brenoepics** [comment]
In GitLab by @Remco on Mar 3, 2022, 11:38

marked the checklist item **NPE** as incomplete
