### ISSUE TITLE
Calendar - can't get currencies

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#708]
In GitLab by @ghost on Jul 4, 2020, 17:14

You can't give currencies in calendar. This is a major function, so kinda sad.

Here's the NPE
```
22:12:07.789 [HabExec-1-7] ERROR com.eu.habbo.messages.PacketManager - Caught exception
java.lang.NullPointerException: null
	at com.eu.habbo.messages.outgoing.events.calendar.AdventCalendarProductComposer.composeInternal(AdventCalendarProductComposer.java:22)
	at com.eu.habbo.messages.outgoing.MessageComposer.compose(MessageComposer.java:19)
	at com.eu.habbo.habbohotel.gameclients.GameClient.sendResponse(GameClient.java:81)
	at com.eu.habbo.habbohotel.catalog.CatalogManager.claimCalendarReward(CatalogManager.java:1151)
	at com.eu.habbo.messages.incoming.events.calendar.AdventCalendarOpenDayEvent.handle(AdventCalendarOpenDayEvent.java:12)
	at com.eu.habbo.messages.PacketManager.handlePacket(PacketManager.java:212)
	at com.eu.habbo.threading.runnables.ChannelReadHandler.run(ChannelReadHandler.java:24)
	at com.eu.habbo.threading.ThreadPooling.lambda$run$0(ThreadPooling.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

this is the queries
```
INSERT INTO `sandbox`.`calendar_rewards`(`id`, `name`, `custom_image`, `credits`, `points`, `points_type`, `badge`, `item_id`) VALUES (3, 'Päivittäinen kolestreak', 'client_static/advent_extras_coins.png', 5000, 0, 0, '', 0);
INSERT INTO `sandbox`.`calendar_rewards`(`id`, `name`, `custom_image`, `credits`, `points`, `points_type`, `badge`, `item_id`) VALUES (4, 'Päivittäinen kolestreak', 'client_static/summer20_clothing_puffyvest.png', 0, 0, 0, '', 14894);
```

**Comment by brenoepics** [comment]
In GitLab by @ghost on Mar 14, 2022, 14:30

Fixed in !486
