### ISSUE TITLE
Wired stacking bug

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#943]
In GitLab by @matotubol on Jan 26, 2021, 19:53

When trying to to move wired and stack them together i get an error

`23:26:46.563 [HabExec-1-6   ] ERROR c.e.h.h.gameclients.GameClient       - Could not pass event com.eu.habbo.plugin.events.furniture.FurnitureMovedEvent to Builders Essentials
23:26:46.563 [HabExec-1-6   ] ERROR c.e.h.h.gameclients.GameClient       - Caught exception
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.eu.habbo.plugin.PluginManager.fireEvent(PluginManager.java:333)
	at com.eu.habbo.habbohotel.rooms.Room.moveFurniTo(Room.java:4621)
	at com.eu.habbo.habbohotel.items.interactions.wired.effects.WiredEffectMatchFurni.execute(WiredEffectMatchFurni.java:77)
	at com.eu.habbo.habbohotel.wired.WiredHandler.lambda$triggerEffect$0(WiredHandler.java:238)
	at com.eu.habbo.threading.ThreadPooling.lambda$run$0(ThreadPooling.java:48)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at com.eu.habbo.buildersessentials.room.SetBuildHeight.onFurnitureMoved(SetBuildHeight.java:44)
	... 15 common frames omitted

`

here is what i mean with stacking.
video
https://streamable.com/czjd0j

**Comment by brenoepics** [comment]
In GitLab by @Harmonic on Mar 3, 2022, 22:32

Contact the developer of the plugin :)
