### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException on answering polls without an answer

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#970]
In GitLab by @Rasmus on May 15, 2021, 06:19

Emulator version: Arcturus Morningstar 3.0.0
Emulator build: 75698c94200c984a3cd80e85577878c3

I created a poll on MS and if i click ok without choosing a option i get the following error

![ztaintTFRx](https://my-gitlab-bucket.s3.amazonaws.com/574591208/ae72056c6af7ff94fbcb8a45cc5579787b228719eb0c4b3b1ea8276c11c8a5d3/ztaintTFRx.mp4)

09:15:12.617 [HabExec-1-1   ] ERROR com.eu.habbo.messages.PacketManager  - Caught exception
java.lang.StringIndexOutOfBoundsException: start 1, end 0, length 0
        at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1724)
        at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:1017)
        at java.base/java.lang.StringBuilder.substring(StringBuilder.java:85)
        at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:968)
        at java.base/java.lang.StringBuilder.substring(StringBuilder.java:85)
        at com.eu.habbo.messages.incoming.polls.AnswerPollEvent.handle(AnswerPollEvent.java:35)
        at com.eu.habbo.messages.PacketManager.handlePacket(PacketManager.java:213)
        at com.eu.habbo.threading.runnables.ChannelReadHandler.run(ChannelReadHandler.java:24)
        at com.eu.habbo.threading.ThreadPooling.lambda$run$0(ThreadPooling.java:48)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by brenoepics** [comment]
In GitLab by @Harmonic on Mar 6, 2022, 22:46

Fixed in 3.1.0
