### ISSUE TITLE
sub cmd npe on not online user

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#975]
In GitLab by @Rasmus on Jun 25, 2021, 10:09

Using the :sub command on a non online user results in a NPE
Cmd used to get this; :sub testuser habbo_club remove

java.lang.NullPointerException: null
        at com.eu.habbo.habbohotel.commands.SubscriptionCommand.handle(SubscriptionCommand.java:74)
        at com.eu.habbo.habbohotel.commands.CommandHandler.handleCommand(CommandHandler.java:88)
        at com.eu.habbo.habbohotel.rooms.Room.talk(Room.java:3170)
        at com.eu.habbo.habbohotel.rooms.Room.talk(Room.java:3097)
        at com.eu.habbo.messages.incoming.rooms.users.RoomUserTalkEvent.handle(RoomUserTalkEvent.java:33)
        at com.eu.habbo.messages.PacketManager.handlePacket(PacketManager.java:213)
        at com.eu.habbo.threading.runnables.ChannelReadHandler.run(ChannelReadHandler.java:24)
        at com.eu.habbo.threading.ThreadPooling.lambda$run$0(ThreadPooling.java:48)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by brenoepics** [comment]
In GitLab by @Rasmus on Jan 18, 2022, 20:05

Fixed in !463
