### ISSUE TITLE
Plugin Load Error?

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#978]
In GitLab by @izzo on Aug 15, 2021, 13:02

Exception in thread "main" java.lang.NoClassDefFoundError: com/eu/habbo/plugin/events/users/UserGetIPAddressEvent
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetPublicMethods(Unknown Source)
        at java.lang.Class.getMethods(Unknown Source)
        at com.eu.habbo.plugin.PluginManager.registerEvents(PluginManager.java:290)
        at org.krews.plugin.nitro.main.onEnable(main.java:21)
        at com.eu.habbo.plugin.PluginManager.loadPlugins(PluginManager.java:276)
        at com.eu.habbo.plugin.PluginManager.reload(PluginManager.java:408)
        at com.eu.habbo.Emulator.main(Emulator.java:142)
Caused by: java.lang.ClassNotFoundException: com.eu.habbo.plugin.events.users.UserGetIPAddressEvent
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.net.FactoryURLClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by brenoepics** [comment]
In GitLab by @brenoepic on Jan 18, 2022, 22:39

Update your morningstar version to 3.0.0
